const SampleReviews = [
  {
    "overallRating": 5,
    "size": 1,
    "comfort": 0,
    "durability": 1,
    "username": "vivaciousVini",
    "reviewTitle": "test",
    "review": "This is simply a test to ensure this project's functionality. The shoes themselves are just alright. Not a huge fan of the Lebrons",
    "country": "United States",
    "city": "Los Angeles",
    "state": "CA",
    "playArea": "I use these casually",
    "offenseStyle": "Drive The Lane",
    "defenseStyle": "Defend the Perimeter",
    "upvote": 13,
    "downvote": 13,
  },
  {
    "overallRating": 5,
    "size": 2,
    "comfort": 2,
    "durability": 2,
    "username": "JustTrent",
    "reviewTitle": "Nothing but magic over here",
    "review": "lauren ipsum something something yada yada whatever",
    "country": "Andorra",
    "city": "Northridge",
    "state": "CA",
    "playArea": "I use these casually",
    "offenseStyle": "Drive The Lane",
    "defenseStyle": "Guard The Ball Handler",
    "upvote": 10,
    "downvote": 6,
  },
  {
    "overallRating": 1,
    "size": 0,
    "comfort": 1,
    "durability": 0,
    "username": "mattThaGenie",
    "reviewTitle": "how many beers",
    "review": "does it take to get to the middle of the dance floor",
    "country": "United States",
    "city": "Los Angeles",
    "state": "CA",
    "playArea": "I use these casually",
    "offenseStyle": "Drive The Lane",
    "defenseStyle": "Defend the Perimeter",
    "upvote": 13,
    "downvote": 13,
  },
];

module.exports = SampleReviews;
